#
# Based on pelson's travis work for cartopy.
#
# Please update the cartopy, test data, and sample data git references below if appropriate.
#
# Note: Contrary to the travis documentation,
# http://about.travis-ci.org/docs/user/languages/python/#Travis-CI-Uses-Isolated-virtualenvs
# we will use the system python because it takes too long to install scipy from source.
#


language: python
python:
  - 2.7
env:
# - INSTALL_OPTIONAL_DEPENDENCIES=true
 - INSTALL_OPTIONAL_DEPENDENCIES=false

git:
  depth: 0

install:

  - export CARTOPY_REF="1fe7438b8f203a19b5855c2491622ee9001bb62c"
  - export CARTOPY_SUFFIX=$(echo "${CARTOPY_REF}" | sed "s/^v//")

  - export IRIS_TEST_DATA_REF="37b937e46f059e1dce4b78a80b323646b8c9ca4c"
  - export IRIS_TEST_DATA_SUFFIX=$(echo "${IRIS_TEST_DATA_REF}" | sed "s/^v//")

  - export IRIS_SAMPLE_DATA_REF="2f279384eab2dcdef1728331ce1b22c95f775437"
  - export IRIS_SAMPLE_DATA_SUFFIX=$(echo "${IRIS_SAMPLE_DATA_REF}" | sed "s/^v//")

  # Switch off virtualenv so we can use apt-get for Python packages.
  - deactivate

  - QUIET=`pwd`/.travis_no_output
  - OPTIONAL=`pwd`/.travis_optional

# add repo
  - $QUIET sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3E5C1192
  - yes | $QUIET sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
  - $QUIET sudo apt-get update

# Get ready...
  - sudo apt-get -qq install python-pip

# Mandatory dependencies
  - $QUIET sudo pip install --use-mirrors mock nose pep8
  - $QUIET sudo apt-get install libudunits2-dev
  - $QUIET sudo apt-get install python-numpy
  # Yucky kludge to install netcdftime (as used by iris.unit).
  - wget http://netcdf4-python.googlecode.com/files/netCDF4-1.0.2.tar.gz
  - tar xzf netCDF4-1.0.2.tar.gz
  - mkdir -p /home/travis/.local/lib/python2.7/site-packages
  - cp netCDF4-1.0.2/netcdftime.py ~/.local/lib/python2.7/site-packages/
  - rm -r netCDF4-1.0.2
  - rm netCDF4-1.0.2.tar.gz
  - ls -l /home/travis/.local/lib/python2.7/site-packages

# Transitional dependencies (i.e. we've not moved them to optional yet!)
  - $QUIET sudo pip install matplotlib==1.2.0
  # Cartopy
  - $QUIET sudo apt-get install cython
  - $QUIET sudo pip install --use-mirrors shapely
  - $QUIET sudo pip install --use-mirrors pyshp
  - $QUIET sudo apt-get install libgeos-dev libproj-dev

# Optional dependencies
  - $OPTIONAL sudo apt-get install python-scipy
  - $OPTIONAL sudo apt-get install libhdf5-serial-dev netcdf-bin libnetcdf-dev
  - $OPTIONAL sudo apt-get install make unzip python-sphinx graphviz
  - $OPTIONAL sudo pip install netCDF4==1.0.2
  - $OPTIONAL sudo pip install pyke pandas
  - $OPTIONAL sudo apt-get install openjdk-7-jre
  - $OPTIONAL sudo apt-get install python-gdal
  - export LD_LIBRARY_PATH=/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server:$LD_LIBRARY_PATH

# cfchecker
  - $OPTIONAL sudo pip install cdat-lite
  - $OPTIONAL sudo pip install cfchecker
# Using table 23 due to a bug present in the current version
  - $OPTIONAL wget http://cf-pcmdi.llnl.gov/documents/cf-standard-names/standard-name-table/23/cf-standard-name-table.xml
#  - $OPTIONAL wget http://cf-pcmdi.llnl.gov/documents/cf-standard-names/standard-name-table/current/cf-standard-name-table.xml
  - $OPTIONAL wget http://cf-pcmdi.llnl.gov/documents/cf-standard-names/area-type-table/current/area-type-table.xml
  - echo '#!/usr/bin/env sh' > cfchecker
  - echo "cfchecks -s `pwd`/cf-standard-name-table.xml -a `pwd`/area-type-table.xml -u /usr/share/xml/udunits/udunits2.xml \$1" >> cfchecker
  - $OPTIONAL sudo cp cfchecker /usr/local/bin/cfchecker
  - $OPTIONAL sudo chmod a+x /usr/local/bin/cfchecker

# grib api
  - $OPTIONAL sudo apt-get install libjasper-dev
  - $OPTIONAL sudo apt-get build-dep libgrib-api-1.9.9 libgrib-api-dev libgrib-api-tools
  - $OPTIONAL wget https://software.ecmwf.int/wiki/download/attachments/3473437/grib_api-1.9.16.tar.gz --no-check-certificate
  - $OPTIONAL tar -xvf grib_api-1.9.16.tar.gz
  - $OPTIONAL cd grib_api-1.9.16/
  - $OPTIONAL CFLAGS="-fPIC" ./configure --with-jasper=/usr/local/lib --disable-fortran --enable-python
  - $OPTIONAL make
  - $OPTIONAL sudo make install
  - $OPTIONAL cd python
  - $OPTIONAL sudo python setup.py install
  - $OPTIONAL cd ../..

# cartopy
  - $QUIET wget -O cartopy.zip https://github.com/SciTools/cartopy/archive/${CARTOPY_REF}.zip
  - $QUIET unzip -q cartopy.zip
  - ln -s $(pwd)/cartopy-${CARTOPY_SUFFIX} cartopy
  - cd cartopy
  - $QUIET python setup.py install --user
  - cd ..

# Pre-load Natural Earth data to avoid multiple, overlapping downloads.
# i.e. There should be no DownloadWarning reports in the log.
  - python -c 'import cartopy; cartopy.io.shapereader.natural_earth()'

# mo_unpack
  - $QUIET wget https://puma.nerc.ac.uk/trac/UM_TOOLS/raw-attachment/wiki/unpack/unpack-030712.tgz
  - $QUIET tar -xf unpack-030712.tgz
  - cd unpack-030712/libmo_unpack
#?  - gcc -c -fPIC -O4 -mfpmath=sse -msse -I include -D_LARGEFILE_SOURCE -D_LARGEFILE_SOURCE64 -D_FILE_OFFSET_BITS=64 *.c
  - $QUIET gcc -c -fPIC -O4 -mfpmath=sse -msse -I include -D_LARGEFILE_SOURCE *.c
  - $QUIET gcc -shared -Wl,-soname,libmo_unpack.so -o lib/libmo_unpack.so *.o
  - $QUIET sudo cp lib/* /usr/local/lib
  - $QUIET sudo cp include/* /usr/local/include
  - cd ../..

# iris test data
  - $QUIET wget -O iris-test-data.zip https://github.com/SciTools/iris-test-data/archive/${IRIS_TEST_DATA_REF}.zip
  - $QUIET unzip -q iris-test-data.zip
  - ln -s $(pwd)/iris-test-data-${IRIS_TEST_DATA_SUFFIX} iris-test-data

# iris sample data
  - $QUIET wget -O iris-sample-data.zip https://github.com/SciTools/iris-sample-data/archive/${IRIS_SAMPLE_DATA_REF}.zip
  - $QUIET unzip -q iris-sample-data.zip
  - ln -s $(pwd)/iris-sample-data-${IRIS_SAMPLE_DATA_SUFFIX} iris-sample-data
  
# iris
  - $QUIET python setup.py --with-unpack build_ext --inplace -I/usr/local/include -L/usr/local/lib -R/usr/local/lib
  - $QUIET python setup.py std_names
  - echo "[Resources]" > lib/iris/etc/site.cfg
  - echo "sample_data_dir = $(pwd)/iris-sample-data/sample_data" >> lib/iris/etc/site.cfg
  - echo "test_data_dir = $(pwd)/iris-test-data/test_data" >> lib/iris/etc/site.cfg
  - ln -s $(pwd)/lib/iris /home/travis/.local/lib/python2.7/site-packages/iris
  - $OPTIONAL python setup.py pyke_rules

  
script:
  - python setup.py test

#  - echo --- RUNNING DOCTESTS ---
#  - cd $(pwd)/docs/iris
#  - make doctest

#  - echo --- RUNNING EXTESTS ---
#  - make extest

